[package]
name = "shaka-sandbox"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
serde.workspace = true
shaka-core = { path = "../shaka-core" }
thiserror.workspace = true
tokio.workspace = true
wasmtime.workspace = true

[dev-dependencies]
serde_json.workspace = true
wat.workspace = true

[lints]
workspace = true
