[package]
name = "shaka-queue"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
chrono.workspace = true
parking_lot.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
hex.workspace = true
shaka-core = { path = "../shaka-core" }
thiserror.workspace = true
uuid = { version = "1.11", features = ["v4", "serde"] }

[lints]
workspace = true
